/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alcancia.vistas;

import alcancia.bo.Alcancia;
import alcancia.dao.AlcaciaDao;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class consultas extends javax.swing.JFrame {

    AlcaciaDao dao = new AlcaciaDao();
    int cincuenta = 50;
    int cien = 100;
    int dociento = 200;
    int quiniento = 500;
    int mil = 200;

    public consultas() {

        initComponents();
        refresar();
        jLabel1.setVisible(false);

        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jSpinner3.setVisible(false);
        jSpinner4.setVisible(false);
        jSpinner5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        mensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        valor50 = new javax.swing.JTextField();
        resultado50 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantidadTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        valor100 = new javax.swing.JTextField();
        resultado100 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        valor200 = new javax.swing.JTextField();
        resultado200 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        valor500 = new javax.swing.JTextField();
        resultado500 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        valor1000 = new javax.swing.JTextField();
        resultado1000 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saldoTotal = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("  $ 50");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jCheckBox2.setText("  $ 100");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 20));

        jCheckBox3.setText("  $  200");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 20));

        jCheckBox4.setText("  $ 500");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, 20));

        jCheckBox5.setText("  $ 1000");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, -1, 20));

        jLabel1.setText("Cantidad: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, 27));

        jLabel2.setText("Cantidad: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 60, 20));

        jLabel3.setText("Cantidad: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, 20));

        jLabel4.setText("Cantidad: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, 20));

        jLabel5.setText("Cantidad: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, -1, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 625, -1, -1));

        jButton1.setBackground(new java.awt.Color(75, 204, 75));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Añadir moneda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        valor50.setEnabled(false);
        valor50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor50ActionPerformed(evt);
            }
        });
        getContentPane().add(valor50, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 80, 30));

        resultado50.setEnabled(false);
        resultado50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado50ActionPerformed(evt);
            }
        });
        getContentPane().add(resultado50, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, 30));

        jLabel6.setText("Monedas de $50");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Monedas Totales");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, 40));

        cantidadTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cantidadTotal.setEnabled(false);
        getContentPane().add(cantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 158, 39));

        jLabel8.setText(" saldo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));

        jCheckBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/50.png"))); // NOI18N
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 80, 30));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 80, 30));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 80, 30));
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 80, 30));
        getContentPane().add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 80, 30));

        jCheckBox7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/200.png"))); // NOI18N
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jCheckBox8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/500.png"))); // NOI18N
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jCheckBox9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1000.png"))); // NOI18N
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, -1, -1));

        jCheckBox10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/100.png"))); // NOI18N
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        valor100.setEnabled(false);
        valor100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor100ActionPerformed(evt);
            }
        });
        getContentPane().add(valor100, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 80, 30));

        resultado100.setEnabled(false);
        resultado100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado100ActionPerformed(evt);
            }
        });
        getContentPane().add(resultado100, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 80, 30));

        jLabel11.setText("Monedas de $100");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 20));

        jLabel12.setText(" saldo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 20));

        valor200.setEnabled(false);
        valor200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor200ActionPerformed(evt);
            }
        });
        getContentPane().add(valor200, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 80, 30));

        resultado200.setEnabled(false);
        resultado200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado200ActionPerformed(evt);
            }
        });
        getContentPane().add(resultado200, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 80, 30));

        jLabel13.setText("Monedas de $200");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel14.setText(" saldo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, 27));

        valor500.setEnabled(false);
        valor500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor500ActionPerformed(evt);
            }
        });
        getContentPane().add(valor500, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 80, 30));

        resultado500.setEnabled(false);
        resultado500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado500ActionPerformed(evt);
            }
        });
        getContentPane().add(resultado500, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 80, 30));

        jLabel15.setText("Monedas de $500");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, 20));

        jLabel16.setText(" saldo");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, 30));

        valor1000.setEnabled(false);
        valor1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1000ActionPerformed(evt);
            }
        });
        getContentPane().add(valor1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 80, 30));

        resultado1000.setEnabled(false);
        resultado1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado1000ActionPerformed(evt);
            }
        });
        getContentPane().add(resultado1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 80, 30));

        jLabel17.setText("Monedas de $1000");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, -1, 20));

        jLabel18.setText(" saldo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Saldo Total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 99, 40));

        saldoTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        saldoTotal.setEnabled(false);
        getContentPane().add(saldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 155, 39));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 1132, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jLabel1.setVisible(true);
            jSpinner1.setVisible(true);
        } else if (!jCheckBox1.isSelected()) {
            jLabel1.setVisible(false);
            jSpinner1.setVisible(false);

        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            jLabel2.setVisible(true);
            jSpinner2.setVisible(true);
        } else if (!jCheckBox2.isSelected()) {
            jLabel2.setVisible(false);
            jSpinner2.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {
            jLabel3.setVisible(true);
            jSpinner3.setVisible(true);
        } else if (!jCheckBox3.isSelected()) {
            jLabel3.setVisible(false);
            jSpinner3.setVisible(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if (jCheckBox4.isSelected()) {
            jLabel4.setVisible(true);
            jSpinner4.setVisible(true);
        } else if (!jCheckBox4.isSelected()) {
            jLabel4.setVisible(false);
            jSpinner4.setVisible(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if (jCheckBox5.isSelected()) {
            jLabel5.setVisible(true);
            jSpinner5.setVisible(true);
        } else if (!jCheckBox5.isSelected()) {
            jLabel5.setVisible(false);
            jSpinner5.setVisible(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mensaje = "";
        if (jCheckBox1.isSelected()) {
            int cantidad = (int) jSpinner1.getValue();
            for (int i = 1; i <= cantidad; i++) {
                mensaje = dao.agregarMoneda(new Alcancia(cincuenta));

            }

        }
        if (jCheckBox2.isSelected()) {
            int cantidad = (int) jSpinner2.getValue();
            for (int i = 1; i <= cantidad; i++) {
                mensaje = dao.agregarMoneda(new Alcancia(cien));
            }

        }
        if (jCheckBox3.isSelected()) {
            int cantidad = (int) jSpinner3.getValue();
            for (int i = 1; i <= cantidad; i++) {
                mensaje = dao.agregarMoneda(new Alcancia(dociento));

            }
        }
        if (jCheckBox4.isSelected()) {
            int cantidad = (int) jSpinner4.getValue();
            for (int i = 1; i <= cantidad; i++) {
                mensaje = dao.agregarMoneda(new Alcancia(quiniento));

            }

        }
        if (jCheckBox5.isSelected()) {
            int cantidad = (int) jSpinner5.getValue();
            for (int i = 1; i <= cantidad; i++) {
                mensaje = dao.agregarMoneda(new Alcancia(mil));

            }
        }
        System.err.println(mensaje);
        refresar();
        JOptionPane.showMessageDialog(null, (mensaje));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void valor50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor50ActionPerformed

    private void resultado50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado50ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void valor100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor100ActionPerformed

    private void resultado100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado100ActionPerformed

    private void valor200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor200ActionPerformed

    private void resultado200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado200ActionPerformed

    private void valor500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor500ActionPerformed

    private void resultado500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado500ActionPerformed

    private void valor1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1000ActionPerformed

    private void resultado1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultado1000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultas().setVisible(true);

            }

        });

    }

    public void refresar() {

        resultado50.setText(dao.consultarMonedas(cincuenta).toString());
        valor50.setText(dao.sumaMonedas(cincuenta).toString());

        resultado100.setText(dao.consultarMonedas(cien).toString());
        valor100.setText(dao.sumaMonedas(cien).toString());

        resultado200.setText(dao.consultarMonedas(dociento).toString());
        valor200.setText(dao.sumaMonedas(dociento).toString());

        resultado500.setText(dao.consultarMonedas(quiniento).toString());
        valor500.setText(dao.sumaMonedas(quiniento).toString());

        resultado1000.setText(dao.consultarMonedas(mil).toString());
        valor1000.setText(dao.sumaMonedas(mil).toString());

        saldoTotal.setText(dao.saldoMonedas().toString());
        cantidadTotal.setText(dao.cantidadMonedas().toString());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField resultado100;
    private javax.swing.JTextField resultado1000;
    private javax.swing.JTextField resultado200;
    private javax.swing.JTextField resultado50;
    private javax.swing.JTextField resultado500;
    private javax.swing.JTextField saldoTotal;
    private javax.swing.JTextField valor100;
    private javax.swing.JTextField valor1000;
    private javax.swing.JTextField valor200;
    private javax.swing.JTextField valor50;
    private javax.swing.JTextField valor500;
    // End of variables declaration//GEN-END:variables
}
